[package]
name = "handflip-core"
version = "0.1.0"
authors = ["Zhe Jiang <nju.jiangzhe@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
futures = "0.3"
async-net = "1.3"
async-executor = "1.1"
thiserror = "1.0"
async-h1 = "2.1"
log = "0.4"
http-types = "2.4"
